version: '3'

services:
  db:
    container_name: SAT_db
    image: mysql:8.0.21
    restart: always
    environment:
      MYSQL_DATABASE: 'SAT'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - '3306'
    ports:
      - 3306:3306
    volumes:
      - ./data-mysql:/var/lib/mysql
    networks:
      - SAT-network

networks:
  SAT-network:
    driver: bridge
